apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["sleep"]
    args: ["99d"]
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
  volumes:
  - name: docker-config
    projected:
      sources:
        - secret:
            name: local-registry-secret
            items:
              - key: .dockerconfigjson
                path: config.json