# add route that allows requests to nexus.local to be forwarded to the Nexus Docker registry service if on port 8082.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-docker-registry
  namespace: nexus
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    ingress.kubernetes.io/proxy-body-size: "0" # Crucial for large image pushes
spec:
  ingressClassName: traefik
  rules:
  - host: nexus.local           # FOR THE WEB UI
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-nexus3
            port:
              number: 8081
  - host: registry.local        # FOR KANIKO/DOCKER PUSH
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-nexus3
            port:
              number: 8082